{% set name = "fmpy" %}
{% set version = "0.2.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}
  
source:
  url: https://github.com/CATIA-Systems/FMPy/archive/v{{ version }}.tar.gz
  sha256: 0984c73e119078f6feadf544dad6908f18d023779dcd2000b69539e14f35d9fc

build:
  number: 1000
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - fmpy = fmpy.command_line:main

requirements:
  build:
    - python
    - pip
  run:
    - dask
    - lxml
    - matplotlib
    - numpy
    - pathlib
    - python
    - pyqt
    - pyqtgraph
    - pywin32  # [win]
    - requests

test:
  imports:
    - fmpy
    - fmpy.cross_check
    - fmpy.examples
    - fmpy.gui
    - fmpy.ssp
    - fmpy.ssp.examples
    - fmpy.sundials

about:
  home: https://github.com/CATIA-Systems/FMPy
  license: BSD-3-Clause
  license_family: BSD
  license_file: '{{ environ["RECIPE_DIR"] }}/LICENSE.txt'
  summary: 'Simulate Functional Mockup Units (FMUs) in Python'

extra:
  recipe-maintainers:
    - t-sommer
    - wulmer
