travis:
  secure:
    BINSTAR_TOKEN: oT1HUxCPUNeLO8rjmircmYRx3kQyQj7dPj/3+KDhisykaP0NXJYywAmC17uYjVcZmysNamklQZuou6jw38rmbGkri+5ZliuyBy7XJCNAdmfduu77DhMd/DnXIX5dPDoXuFlamXhSuen+qTc08diJ+ylhsTjxWGsDhnsfR9iCMBSY9xkw1Y4XM9ca1Nmr9NpDMirNas3Q6mVtsL06GH+zdxIOYr9gw9YooDwOoPa+wo99UhUTI0K9OKUMl8zqYDB6g+pgKW9YFtxkOxjKW/NIEcXKUAmgmzs6Z1U9w/BtL3IL9UNnfncrS4o4VjTpbIO2PYHqs3HEHQj/lM9p9XUC1j+VkpZgtBVoDiSHMHEKHlmbdXhCitX0FUKBq0PgKUwK7vv532NWWPcEMjCIb5iGnU0J65UUr2M+5IcFdqML7S0bgUPJCxjrLI91jYuB7LWoGJwXj+LbADebCd+O4ouUYy7XcEHCF+x7xKQ+7axLLngnN6NzZlLE9nDAOiQnIyJk00501qmzbjxRx81F2B2D7MGdFA4tOsJ84+k25JRNVnaaobaRdyPHbz0CMp+r4gwLbsnydIBpKltHoCEPAC9kgpdoV9uXPAhLoVrp2SBtOQHZ3jaVA7D0ibYeieF0zW8DqPfdj80nRhARClyonhA5t0OSujNIjOsVpigTU8ORv1A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
