travis:
  secure:
    BINSTAR_TOKEN: p+DK6Nko3J7dFcTAatn6TXdRahS7mNBqkBaL5BLLwrmzXaFgyNge2CB/7LY5/cUzsVJ5GsY//6SbVkkC9etT+XuRC5jVSFDTs8bj5Vl3uycAosPJ6ZIkon5dTZyTbj57lTNI/MAKdXcc1AvJmrxFAfCMADB++ahgU5HzkIUrBezN9U9ZBehBnje+dnEXtssA6hrXEJXonL9xF0QQqHP7rx1wbKleHY+yAjGdULgrex0noWzizaQHLnTNisAtBFD0muo1B6po/lrt998WjAPXeLLrznOo2CtuKs+ZLl8gwYz6IEZ024rOd1roL6tozmSYRWQ25uvWrqg45RNrFxOpx5VCEWxZdHR6oiUbFWLQbFqmPATcelcfbDzUIGKC281ed7SeAuNNakDRg2lSky8h/YpUZ98Y1JtaHbroStEG2i+6/IjjUHrMRYJJjAuqtsUo4oZEfv24QNDjtwjH/HMbbaF/VevdSBZdmFj5ug9/TD1thYiRvJPjyr0mSJGVkTOwOjBlD3e2EIgyBWOEOnErxLTnExv0yNWW0nyGGmYMXbQp8uClTcosbmhUMaon5xPGw7w99WrNVpK89YGtcdBPPXnqfTLuLWv1A9yng/xsZ9GStEZMk3R3R4zCRHBGvxvKZ9yesp5Z6NNYzwlPxWGaIosI3T5vE0R0ZrvmgoNZ9GU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
